### ISSUE TITLE
After VS Studio throws an unrecoverable error, Theme gets "unloaded"

### ISSUE THREAD

**Issue by Stani1k** [jflepp/JFlepp.VS.Theme.DarkYellow#6] opened 2021-02-12 18:08 UTC
Hello,
first of all, I really like your Theme and thanks for the work you provide.

I have a problem when e.x. I copy some text in VS Studio and it throws an unrecoverable error. After that when I'm writing code the colors for classes etc. don't appear again.. 
Here is an example how it looks like, after the error occurs:
![image](https://user-images.githubusercontent.com/71967305/107804939-e9b45980-6d64-11eb-931f-3d9e76efb4c8.png)

As you can see the color from the class just disappeared. Closing and reopening the document don't help. I need to close and open Visual Studio again and that's a bit annoying.

Here is the StackTrace i saved when it occured last time:

> System.OperationCanceledException : The operation was canceled.
>    at System.Threading.CancellationToken.ThrowOperationCanceledException()
>    at System.IO.Pipes.NamedPipeServerStream.EndWaitForConnection(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,Func`2 endFunction,Action`1 endAction,Task`1 promise,Boolean requiresSynchronization)
>    at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](<Unknown Parameters>)
> 

Any ideas why this is hapenning?

**Comment by fl3pp** [comment] 2021-02-12 20:31
Hi @Stani1k,

Glad you like the theme.

This looks like VS crashes because of a bug in VS itself or a plugin. VS then stops providing language features and the editor can thus not color the code correctly. I suspect you could reproduce this error using a built-in theme (some elements are just white).

As this theme does not contain any code, we can _almost_ be sure that the theme does not cause this behavior, but reproducing the error with a built-in theme would prove this. I'm going forward and close this issue, if you can't reproduce the error with a built-in theme you can reply here again and I will take a closer look.

I'm sorry if I can't offer you better help but I suggest you direct your investigation to VS or maybe some plugin you have installed.

Best regards

**Closed as completed by fl3pp** 2021-02-12 20:31 UTC

**Comment by Stani1k** [comment] 2021-02-17 12:01
Hello @jflepp,

thanks for your fast reply. I will use the default theme for a while and see if I can reproduce the error and will let you know.

I have another question and hope it's okay that I ask it here. I'm wondering if you could provide a version which works with ReSharper and their additional features. Because at the beginning I needed to change some item colors for ReSharper as because of the Theme, the colors were inappropriate.

For example I'm using the "Unit Test Sessions" window from ReSharper and the namespace colors are are hardly recognizable.
![image](https://user-images.githubusercontent.com/71967305/108201468-27780000-7120-11eb-84b0-58ab08c95414.png)

I would need to change it manually, but maybe there is something you could provide us?

**Comment by fl3pp** [comment] 2021-02-17 13:30
Hi @Stani1k,

I do not use ReSharper and an evaluation version wouldn't allow me to check updates in the future. So I don't think I will add official support.

What I can offer you is that I'll take a look at a PR with your settings if you provide me one. You can do it like this:

Take a look at your `*.vsssettings` file (Tools -> Options -> Environment -> Import and Export Settings), you can check there which adjustments you've made (export, change in VS, export again, compare). The [vstheme](https://github.com/jflepp/JFlepp.VS.Theme.DarkYellow/blob/master/JFlepp.VS.Theme.DarkYellow/CustomTheme.vstheme) file is nothing else than just a collection of such settings (in a slightly different format) that will be applied when activating the theme. This is basically all this theme is about. You can add your settings to the file using a simple XML editor.

If you need help doing that, you can respond here again.
