### ISSUE TITLE
Search text not visible

### ISSUE THREAD

**Issue by folkcoder** [jflepp/JFlepp.VS.Theme.DarkYellow#11] opened 2021-11-23 13:23 UTC
When searching using the Find and Replace control, the text in the focused textbox is not visible. Once the user clicks outside the Find and Replace control, the text becomes visible. This behavior does not occur using the built-in dark theme.

![darkyellow-visibility-bug](https://user-images.githubusercontent.com/28113433/143031687-c7ecadff-7b41-4860-baa3-f5d3e2a4c9c8.gif)

**Comment by fl3pp** [comment] 2021-11-27 18:45
Hi @folkcoder,

Thanks for posting the issue.
I could reproduce your behavior and uploaded version 2.2 which should fix the issue. May you please check?

Best Regards

**Comment by fl3pp** [comment] 2021-11-29 06:54
Closing this issue since it has been resolved

**Closed as completed by fl3pp** 2021-11-29 06:54 UTC

**Comment by folkcoder** [comment] 2021-11-29 12:03
@jflepp I tested on my end and it works great. Thank you for fixing this so quickly!
